### ISSUE TITLE
Errors adding dataTable.helpers.js or dataTable.js

### ISSUE THREAD

**Issue by stoplion** [Swimlane/angular-data-table#127]
Errors when adding dataTable.helpers.js 

**[Example Repo](https://github.com/stoplion/ng-table-test)**

```
TypeError: Cannot read property 'columns' of undefined
    at new BodyController (http://localhost:4567/javascripts/all.js:66073:37)
    at Object.invoke (http://localhost:4567/javascripts/all.js:35783:17)
    at extend.instance (http://localhost:4567/javascripts/all.js:40073:21)
    at http://localhost:4567/javascripts/all.js:39319:13
    at forEach (http://localhost:4567/javascripts/all.js:31911:20)
    at nodeLinkFn (http://localhost:4567/javascripts/all.js:39318:11)
    at compositeLinkFn (http://localhost:4567/javascripts/all.js:38697:13)
    at nodeLinkFn (http://localhost:4567/javascripts/all.js:39343:24)
    at compositeLinkFn (http://localhost:4567/javascripts/all.js:38697:13)
    at compositeLinkFn (http://localhost:4567/javascripts/all.js:38700:13) <div ui-view="" class="ng-scope">(anonymous function) @ all.js:43235(anonymous function) @ all.js:40176invokeLinkFn @ all.js:39840nodeLinkFn @ all.js:39348compositeLinkFn @ all.js:38697publicLinkFn @ all.js:38576updateView @ all.js:61849(anonymous function) @ all.js:61811Scope.$broadcast @ all.js:46365$state.transition.resolved.then.$state.transition @ all.js:61201processQueue @ all.js:44828(anonymous function) @ all.js:44844Scope.$eval @ all.js:46046Scope.$digest @ all.js:45862Scope.$apply @ all.js:46151bootstrapApply @ all.js:33035invoke @ all.js:35783doBootstrap @ all.js:33033bootstrap @ all.js:33053angularInit @ all.js:32947(anonymous function) @ all.js:57884fire @ all.js:3100self.fireWith @ all.js:3212jQuery.extend.ready @ all.js:3418completed @ all.js:3434
2016-01-07 20:02:07.866 all.js:43235 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (all.js:66669)
    at $parseFunctionCall (all.js:43984)
    at Object.regularInterceptedExpression (all.js:44490)
    at Scope.$digest (all.js:45880)
    at Scope.$apply (all.js:46151)
    at bootstrapApply (all.js:33035)
    at Object.invoke (all.js:35783)
    at doBootstrap (all.js:33033)
    at bootstrap (all.js:33053)
    at angularInit (all.js:32947)(anonymous function) @ all.js:43235(anonymous function) @ all.js:40176Scope.$digest @ all.js:45906Scope.$apply @ all.js:46151bootstrapApply @ all.js:33035invoke @ all.js:35783doBootstrap @ all.js:33033bootstrap @ all.js:33053angularInit @ all.js:32947(anonymous function) @ all.js:57884fire @ all.js:3100self.fireWith @ all.js:3212jQuery.extend.ready @ all.js:3418completed @ all.js:3434
2016-01-07 20:02:07.866 all.js:43235 TypeError: Cannot read property 'total' of undefined
    at HeaderController.innerStyles (all.js:66643)
    at $parseFunctionCall (all.js:43984)
    at Object.regularInterceptedExpression (all.js:44490)
    at Scope.$digest (all.js:45880)
    at Scope.$apply (all.js:46151)
    at bootstrapApply (all.js:33035)
    at Object.invoke (all.js:35783)
    at doBootstrap (all.js:33033)
    at bootstrap (all.js:33053)
    at angularInit (all.js:32947)(anonymous function) @ all.js:43235(anonymous function) @ all.js:40176Scope.$digest @ all.js:45906Scope.$apply @ all.js:46151bootstrapApply @ all.js:33035invoke @ all.js:35783doBootstrap @ all.js:33033bootstrap @ all.js:33053angularInit @ all.js:32947(anonymous function) @ all.js:57884fire @ all.js:3100self.fireWith @ all.js:3212jQuery.extend.ready @ all.js:3418completed @ all.js:3434
2016-01-07 20:02:07.867 all.js:43235 TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (all.js:66635)
    at $parseFunctionCall (all.js:43984)
    at Object.regularInterceptedExpression (all.js:44490)
    at Scope.$digest (all.js:45880)
    at Scope.$apply (all.js:46151)
    at bootstrapApply (all.js:33035)
    at Object.invoke (all.js:35783)
    at doBootstrap (all.js:33033)
    at bootstrap (all.js:33053)
    at angularInit (all.js:32947)

  .... constant error
```

Adding dataTable.js
`all.js:65349 Uncaught ReferenceError: babelHelpers is not defined`

I'm install this through Bower. 

![image](https://cloud.githubusercontent.com/assets/231343/12214697/dc2bfbf6-b653-11e5-801e-dbef8aa27440.png)

![image](https://cloud.githubusercontent.com/assets/231343/12214698/ea83aece-b653-11e5-86e8-97c175242d28.png)

**Comment by amcdnl** [comment]
same as #90

**Comment by stoplion** [comment]
since this issue is still happening maybe one issue should remain open? (#90 is also closed)
