### ISSUE TITLE
ReferenceError: Can't find variable: babelHelpers

### ISSUE THREAD

**Issue by idot** [Swimlane/angular-data-table#187]
I have seen #114  #111 #112 #13 which are all closed, but the problem is there with a new project started from scratch with the popular https://github.com/Swiip/generator-gulp-angular

```
> mkdir testDT
> cd testDT
> yo gulp-angular
```

```
? Which version of Angular do you want? 1.5.x (stable)
? What Angular modules would you like to have? (ngRoute and ngResource will be addressed after) angular-animate.js (enable animation features), angular-cookies.js (handle cookie m
anagement), angular-touch.js (for mobile development), angular-sanitize.js (to securely parse and manipulate HTML), angular-messages.js (enhanced support for displaying messages w
ithin templates), angular-aria.js (support for common ARIA attributes)
? Do you need jQuery or perhaps Zepto? None (Angular will use its own jqLite)
? Would you like to use a REST resource library? Restangular, an alternative service to handle RESTful requests
? Would you like to use a router? UI Router, flexible routing with nested views
? Which UI framework do you want? Angular Material, the reference implementation of the Google's Material Design specification
? Which CSS preprocessor do you want? Sass (Node), Node.js binding to libsass, the C version of the popular stylesheet preprocessor, Sass.
? Which JS preprocessor do you want? None, I like to code in standard JavaScript.
? Which HTML template engine would you want? None, I like to code in standard HTML.
```

```
> gulp test
[19:16:58] Using gulpfile ~/xtmp/testDT/gulpfile.js
[19:16:58] Starting 'scripts'...
[19:16:59] all files 14.01 kB
[19:16:59] Finished 'scripts' after 1.11 s
[19:16:59] Starting 'test'...
27 04 2016 19:17:00.014:WARN [watcher]: Pattern "/Users/ido.tamir/xtmp/testDT/src/**/*.mock.js" does not match any file.
PhantomJS 1.9.8 (Mac OS X 0.0.0): Executed 18 of 18 SUCCESS (0.1 secs / 0.655 secs)
[19:17:02] Finished 'test' after 2.75 s
ido.tamir@nbm-vbcf-18 ~/xtmp/testDT>  bower install angular-data-table --save
bower                     invalid-meta The "name" is recommended to be lowercase, can contain digits, dots, dashes
bower angular-data-table#*      cached https://github.com/Swimlane/angular-data-table.git#0.4.15
bower angular-data-table#*    validate 0.4.15 against https://github.com/Swimlane/angular-data-table.git#*
bower angular-data-table#^0.4.15          install angular-data-table#0.4.15

angular-data-table#0.4.15 bower_components/angular-data-table
ido.tamir@nbm-vbcf-18 ~/xtmp/testDT> gulp test
[19:17:22] Using gulpfile ~/xtmp/testDT/gulpfile.js
[19:17:22] Starting 'scripts'...
[19:17:23] all files 14.01 kB
[19:17:23] Finished 'scripts' after 916 ms
[19:17:23] Starting 'test'...
27 04 2016 19:17:23.458:WARN [watcher]: Pattern "/Users/ido.tamir/xtmp/testDT/src/**/*.mock.js" does not match any file.
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  ReferenceError: Can't find variable: babelHelpers
  at /Users/ido.tamir/xtmp/testDT/bower_components/angular-data-table/release/dataTable.js:89


[19:17:25] 'test' errored after 1.91 s
[19:17:25] Error: Failed 1 tests.
    at /Users/ido.tamir/xtmp/testDT/gulp/unit-tests.js:41:22
    at removeAllListeners (/Users/ido.tamir/xtmp/testDT/node_modules/karma/lib/server.js:336:7)
    at Server.<anonymous> (/Users/ido.tamir/xtmp/testDT/node_modules/karma/lib/server.js:347:9)
    at Server.g (events.js:273:16)
    at emitNone (events.js:85:20)
    at Server.emit (events.js:179:7)`
```

**Comment by ghost** [comment]
Are your tests only unit tests?
If so, you can remove this library from the loaded ones and only test your angular sources.
Does that help?

**Comment by amcdnl** [comment]
@idot you are not including the correct file. 

`ReferenceError: Can't find variable: babelHelpers
  at /Users/ido.tamir/xtmp/testDT/bower_components/angular-data-table/release/dataTable.js:89`

is occurring because you are either not using babel OR not using the correct build for your setup. See https://github.com/Swimlane/angular-data-table#include
