### ISSUE TITLE
Error: [ng:areq] Argument 'module' is not a function, got Object

### ISSUE THREAD

**Issue by trusktr** [Swimlane/angular-data-table#189]
Getting the following error after importing `release/dataTable.helpers.js`:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module {"_invokeQueue":[["$compileProvider","directive",{"0":"dtable"}],["$compileProvider","directive",{"0":"resizable"}],["$compileProvider","directive",{"0":"sortable"}],["$compileProvider","directive",{"0":"dtHeader"}],["$compileProvider","directive",{"0":"dtHeaderCell"}],["$compileProvider","directive",{"0":"dtBody"}],["$compileProvider","directive",{"0":"dtScroller"}],["$compileProvider","directive",{"0":"dtSeletion"}],["$compileProvider","directive",{"0":"dtRow"}],["$compileProvider","directive",{"0":"dtGroupRow"}],["$compileProvider","directive",{"0":"dtCell"}],["$compileProvider","directive",{"0":"dtFooter"}],["$compileProvider","directive",{"0":"dtPager"}]],"_configBlocks":[],"_runBlocks":[],"requires":[],"name":"data-table"} due to:
Error: [ng:areq] Argument 'module' is not a function, got Object
http://errors.angularjs.org/1.5.5/ng/areq?p0=module&p1=not%20a%20function%2C%20got%20Object
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:68:12)
    at assertArg (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:1880:11)
    at assertArgFn (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:1890:3)
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4573:11)
    at forEach (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:322:20)
    at loadModules (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4548:5)
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4565:40)
    at forEach (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:322:20)
    at loadModules (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4548:5)
    at createInjector (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4470:19)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=%7B%22_invokeQueue%22%3A%5B%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22resizable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sortable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtHeader%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtHeaderCell%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtBody%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtScroller%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtSeletion%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtRow%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtGroupRow%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtCell%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtFooter%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtPager%22%7D%5D%5D%2C%22_configBlocks%22%3A%5B%5D%2C%22_runBlocks%22%3A%5B%5D%2C%22requires%22%3A%5B%5D%2C%22name%22%3A%22data-table%22%7D&p1=Error%3A%20%5Bng%3Aareq%5D%20Argument%20'module'%20is%20not%20a%20function%2C%20got%20Object%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2Fng%2Fareq%3Fp0%3Dmodule%26p1%3Dnot%2520a%2520function%252C%2520got%2520Object%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A68%3A12)%0A%20%20%20%20at%20assertArg%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1880%3A11)%0A%20%20%20%20at%20assertArgFn%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1890%3A3)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4573%3A11)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4565%3A40)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20createInjector%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4470%3A19)
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:68:12)
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4587:15)
    at forEach (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:322:20)
    at loadModules (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4548:5)
    at eval (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4565:40)
    at forEach (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:322:20)
    at loadModules (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4548:5)
    at createInjector (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:4470:19)
    at doBootstrap (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:1746:20)
    at bootstrap (eval at <anonymous> (http://localhost:8080/app.bundle.js:511:2), <anonymous>:1767:12)
http://errors.angularjs.org/1.5.5/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20%7B%22_invokeQueue%22%3A%5B%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22resizable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22sortable%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtHeader%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtHeaderCell%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtBody%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtScroller%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtSeletion%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtRow%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtGroupRow%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtCell%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtFooter%22%7D%5D%2C%5B%22%24compileProvider%22%2C%22directive%22%2C%7B%220%22%3A%22dtPager%22%7D%5D%5D%2C%22_configBlocks%22%3A%5B%5D%2C%22_runBlocks%22%3A%5B%5D%2C%22requires%22%3A%5B%5D%2C%22name%22%3A%22data-table%22%7D%20due%20to%3A%0AError%3A%20%5Bng%3Aareq%5D%20Argument%20'module'%20is%20not%20a%20function%2C%20got%20Object%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2Fng%2Fareq%3Fp0%3Dmodule%26p1%3Dnot%2520a%2520function%252C%2520got%2520Object%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A68%3A12)%0A%20%20%20%20at%20assertArg%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1880%3A11)%0A%20%20%20%20at%20assertArgFn%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1890%3A3)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4573%3A11)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4565%3A40)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20createInjector%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4470%3A19)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.5%2F%24injector%2Fmodulerr%3Fp0%3D%257B%2522_invokeQueue%2522%253A%255B%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtable%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522resizable%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522sortable%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtHeader%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtHeaderCell%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtBody%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtScroller%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtSeletion%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtRow%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtGroupRow%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtCell%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtFooter%2522%257D%255D%252C%255B%2522%2524compileProvider%2522%252C%2522directive%2522%252C%257B%25220%2522%253A%2522dtPager%2522%257D%255D%255D%252C%2522_configBlocks%2522%253A%255B%255D%252C%2522_runBlocks%2522%253A%255B%255D%252C%2522requires%2522%253A%255B%255D%252C%2522name%2522%253A%2522data-table%2522%257D%26p1%3DError%253A%2520%255Bng%253Aareq%255D%2520Argument%2520'module'%2520is%2520not%2520a%2520function%252C%2520got%2520Object%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.5%252Fng%252Fareq%253Fp0%253Dmodule%2526p1%253Dnot%252520a%252520function%25252C%252520got%252520Object%250A%2520%2520%2520%2520at%2520eval%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A68%253A12)%250A%2520%2520%2520%2520at%2520assertArg%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A1880%253A11)%250A%2520%2520%2520%2520at%2520assertArgFn%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A1890%253A3)%250A%2520%2520%2520%2520at%2520eval%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A4573%253A11)%250A%2520%2520%2520%2520at%2520forEach%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A322%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A4548%253A5)%250A%2520%2520%2520%2520at%2520eval%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A4565%253A40)%250A%2520%2520%2520%2520at%2520forEach%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A322%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A4548%253A5)%250A%2520%2520%2520%2520at%2520createInjector%2520(eval%2520at%2520%253Canonymous%253E%2520(http%253A%252F%252Flocalhost%253A8080%252Fapp.bundle.js%253A511%253A2)%252C%2520%253Canonymous%253E%253A4470%253A19)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A68%3A12)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4587%3A15)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20eval%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4565%3A40)%0A%20%20%20%20at%20forEach%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A322%3A20)%0A%20%20%20%20at%20loadModules%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4548%3A5)%0A%20%20%20%20at%20createInjector%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A4470%3A19)%0A%20%20%20%20at%20doBootstrap%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1746%3A20)%0A%20%20%20%20at%20bootstrap%20(eval%20at%20%3Canonymous%3E%20(http%3A%2F%2Flocalhost%3A8080%2Fapp.bundle.js%3A511%3A2)%2C%20%3Canonymous%3E%3A1767%3A12)
```

**Comment by amcdnl** [comment]
Can you provide a demo?

**Comment by mikkelking** [comment]
I had the same problem, and ended up working it out. Hopefully yours is related.

If you have done this:

```
import MyModule from '../mymodule/mymodule'
```

and then referenced it like this:

```
// create a module
export default angular.module(name, [
  angularMeteor
  ,uiRouter
  ,MyModule
...
```

Then you need to either change your import statement to this:

```
import {name as MyModule} from '../mymodule/mymodule'
```

or change your reference to this:

```
// create a module
export default angular.module(name, [
  angularMeteor
  ,uiRouter
  ,'mymodule'
...
```

The difference is very subtle, but now I know how to fix it :)

**Comment by pranavkumar** [comment]
sorry. i tried to import d3 js like that. it did not work.
