### ISSUE TITLE
It  dones  not work  in  IE11

### ISSUE THREAD

**Issue by guo-guo** [Swimlane/angular-data-table#264]
```
**### TypeError: 对象不支持“assign”属性或方法
at DataTableController (http://192.168.0.150/app/libs/angular-data-table/dataTable.js:2066:7)
at invoke (http://192.168.0.150/app/libs/angular/angular.min.js:41:225)
at Anonymous function (http://192.168.0.150/app/libs/angular/angular.min.js:86:436)
.........**
```
Please tell me How to solve it?  Thankyou

**Comment by jonshaffer** [comment]
Can you make a demo on Codepen to reproduce this?

I'm involved in a team that's releasing an app that supports IE 11 and have had no browser specific issues yet

**Comment by guo-guo** [comment]
@jonshaffer  It works in firefox and chrome but not worked in IE11 . The error is "TypeError: Object does not support "assign" properties or methods"  in  IE11

**Comment by guo-guo** [comment]
I  had resolve it.   
```
$.extend(true,this,{
        $scope: $scope,
        $filter: $filter,
        $log: $log
      });

      /*Object.assign(this, {
        $scope: $scope,
        $filter: $filter,
        $log: $log
      });*/
```

**Comment by guo-guo** [comment]
I had to solve it .
```
$.extend(true,this,{
      $scope: $scope,
      $filter: $filter,
      $log: $log
  });

  /*Object.assign(this, {
       $scope: $scope,
       $filter: $filter,
       $log: $log
   });*/
```
