### ISSUE TITLE
Live demo are not working

### ISSUE THREAD

**Issue by mrtinkz** [Swimlane/angular-data-table#84]
Sorry for the elobrated but the demo does not seems to be working.

http://swimlane.github.io/angular-data-table/

icon $default:menu not found
dataTable.js:81 Uncaught ReferenceError: babelHelpers is not defined
angular.min.js:102 TypeError: Cannot read property 'length' of undefined
    at DataTableController.transposeColumnDefaults (https://cdn.rawgit.com/Swimlane/angular-data-table/gh-pages/lib/dataTable.helpers.js:1964:51)
    at pre (https://cdn.rawgit.com/Swimlane/angular-data-table/gh-pages/lib/dataTable.helpers.js:2157:18)
    at Z (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:70:149)
    at A (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:59:14)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:299)
    at A (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:59:147)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:299)
    at g (http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:51:316)
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:50:415
    at http://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.14/angular.min.js:18:8 <div class="material dt ng-scope" ng-class="dt.tableCss()" data-column-id="560827780a5902e059708c63" options="options" rows="data">(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'columns' of undefined
    at new BodyController (dataTable.helpers.js:800)
    at Object.e [as invoke](angular.min.js:36)
    at w.instance (angular.min.js:75)
    at angular.min.js:58
    at s (angular.min.js:7)
    at A (angular.min.js:58)
    at g (angular.min.js:51)
    at A (angular.min.js:59)
    at g (angular.min.js:51)
    at A (angular.min.js:59)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'length' of undefined
    at Object.fn (dataTable.helpers.js:1922)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at angular.min.js:17
    at Object.e [as invoke](angular.min.js:36)
    at d (angular.min.js:17)
    at tc (angular.min.js:18)
    at Jd (angular.min.js:17)
    at angular.min.js:249
    at HTMLDocument.a (angular.min.js:163)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at angular.min.js:17
    at Object.e [as invoke](angular.min.js:36)
    at d (angular.min.js:17)
    at tc (angular.min.js:18)
    at Jd (angular.min.js:17)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'total' of undefined
    at HeaderController.innerStyles (dataTable.helpers.js:1306)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at angular.min.js:17
    at Object.e [as invoke](angular.min.js:36)
    at d (angular.min.js:17)
    at tc (angular.min.js:18)
    at Jd (angular.min.js:17)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (dataTable.helpers.js:1298)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at angular.min.js:17
    at Object.e [as invoke](angular.min.js:36)
    at d (angular.min.js:17)
    at tc (angular.min.js:18)
    at Jd (angular.min.js:17)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at angular.min.js:17
    at Object.e [as invoke](angular.min.js:36)
    at d (angular.min.js:17)
    at tc (angular.min.js:18)
    at Jd (angular.min.js:17)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'center' of undefined
    at HeaderController.stylesByGroup (dataTable.helpers.js:1320)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at S (angular.min.js:85)
    at XMLHttpRequest.D.onload (angular.min.js:86)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'total' of undefined
    at HeaderController.innerStyles (dataTable.helpers.js:1306)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at S (angular.min.js:85)
    at XMLHttpRequest.D.onload (angular.min.js:86)(anonymous function) @ angular.min.js:102
angular.min.js:102 TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (dataTable.helpers.js:1298)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at S (angular.min.js:85)
    at XMLHttpRequest.D.onload (angular.min.js:86)(anonymous function) @ angular.min.js:102

**Comment by frontich** [comment]
as  @marjan-georgiev  stated in  https://github.com/Swimlane/angular-data-table/issues/80 the examples are out of date... he is going to update them soon.

**Comment by trusktr** [comment]
This is a bug. #187
